name = "diskprune-licensing"
main = "src/index.js"
compatibility_date = "2024-03-01"

[[routes]]
pattern = "api.diskprune.com"
custom_domain = true

[[kv_namespaces]]
binding = "LICENSES"
id = "c273cf8e9c864d5bbd46840db2a7f153"
